### ISSUE TITLE
React router compat

### ISSUE THREAD

**Issue by tj** [developit/preact-compat#47]
I'm looking into the issue but I was curious if anyone has this working with react-router as well. Somehow route matching is broken (after using aliasify). I'll post back if I figure out what's up.

**Comment by developit** [comment]
I recall someone posting about using them together, but can't seem to find it.  I'm interested in making them play nice though, any errors/repos help emensely.

**Comment by tj** [comment]
Too lazy to dig around today haha, but there was no exception, just a warning message saying it couldn't match, which is odd, the Redux input is identical. Seems like all of the React methods are there, otherwise it would be throwing, so there must be a tiny incompatibility somewhere

**Comment by developit** [comment]
Ah no probem haha. This has me thinking it's something to do with the internal shape of the VNode, but that's a bit of a guess. I will send about putting a demo together today.

**Comment by tylerbwilliams** [comment]
Found the issue that causes `react-router` to fail.  React Router uses the `props.children` attribute to iterate over nested `Route`s.  When using `preact-compat` to emulate the `props` attribute, it fails to insert the `children` property back in with `attributes`.

`preact-compat` - Aliases the attributes property, but doesn't add back the `children` attribute React uses
https://github.com/developit/preact-compat/blob/master/src/index.js#L45

`react-router` - Creates a "route" from the `props` of an element, assumes there is a `children` property
https://github.com/reactjs/react-router/blob/master/modules/RouteUtils.js#L38

**Comment by developit** [comment]
Interesting. Might already have a fix for this locally then, will try to get it out in short order.

**Comment by tylerbwilliams** [comment]
Any ETA on this?

**Comment by developit** [comment]
I've knocked out all the other top priority bugs and I'm working on compatibility stuff now.  I'll keep you posted!

**Comment by kay-is** [comment]
I get an error with Reat-Router too.

The console logs:

    Uncaught Error: Required prop `createElement` was not specified in `<<anonymous>>`.

It seems to originate from:

https://github.com/developit/preact-compat/blob/master/src/index.js#L276

`prop` is `'createElement'` and `this.displayName` is `'RouterContext'` when it fails

**Comment by developit** [comment]
Do any of you have repos / repros I could take a look at for this?  I want to make sure I'm testing against the setup that is breaking here.  Thanks!

**Comment by idchlife** [comment]
It seems it just wont work for me. I did as in readme, about resole and alias, but I just see plain page and this:

![image](https://cloud.githubusercontent.com/assets/4563032/16155847/e6ab4eda-34b9-11e6-80c0-a0c08cd338b6.png)


My code:

![image](https://cloud.githubusercontent.com/assets/4563032/16155821/ceed2a34-34b9-11e6-81ba-ce40d1e8ed1b.png)

Index and Error404 function components with simple div+text returned.

**Comment by developit** [comment]
I need to have `preact-compat` alias `props.children`. This will require Preact 5 (beta) FYI

**Comment by idchlife** [comment]
@developit what should I do? Install latest preact and alias 'props.children': 'preact-compat'? :o

**Comment by developit** [comment]
Just working on an update to patch this and one other issue using preact 5 with preact-compat. Expect a release there shortly.

**Comment by developit** [comment]
Commit auto-closed, which was probably a little hopeful on my part.  If anyone can give this a whirl if you still have a breaking example, let me know if it's working now!

**Comment by idchlife** [comment]
@developit lastest preact and preact-compat 1.8.0 with latest react-router. Stil... blank page with this:

![image](https://cloud.githubusercontent.com/assets/4563032/16186463/56d336da-36d3-11e6-818a-e7a29d6503ba.png)


In package.json:


![image](https://cloud.githubusercontent.com/assets/4563032/16186452/3607f7ba-36d3-11e6-8d97-b2a6b7215a19.png)

**Comment by idchlife** [comment]
@developit unfortunately there is global problem with rendering with preact 5 beta. I'm not getting even render of simple things. Old scripts are broken, I have white pages but components somehow works inside (console.log in render)

Now downgrading to 4.8.0

**Comment by developit** [comment]
@idchlife ping me on Gitter if you can - I just published `5.0.1-beta.15` that fixes a bug caused by overzealous minification, was resulting in some very very strange behavior (random elements added/removed, etc) due to a loop variable not being reset on each iteration causing fall-through.

**Comment by kay-is** [comment]
@developit Still not working.

Had a bit time to try out with the current versions. (preact 5.1.0-beta.19 and preact-compat 1.8.1)

https://github.com/developit/preact-compat/blob/1.8.1/src/index.js#L300

The `createElement` prop is still missing for the `RouterContext` component.

There is a key `createElement` in `props` but it's `undefined` and it seems to be the only undefined there. `components`, `history`, `location`, `params`, `router` and `routes` all have values.

When running in `production` mode `RouterContext` really seems to call `this.props.createElement()` (which is missing then) so this doesn't seem to be a wrong alarm.

**Comment by developit** [comment]
Hmm - this points to it being an issue with `getDefaultProps()` in preact-compat. Looking there now.

**Comment by developit** [comment]
This is very strange - I can't reproduce the defaultProps issue in isolation:  https://jsfiddle.net/developit/2vtwzbng/7/

@kay-is if you still have this running somewhere, any chance you can check if `RouterContext`'s `getDefaultProps()` is even being called?  Or if `this.constructor.defaultProps` is properly set on the instance you were looking at.

**Comment by kay-is** [comment]
`getDefaultProps()` of `RouterContext` is called once.

`this.constructor.defaultProps` is `{createElement: function createElement()}` when I got to the line where the error is thrown.

**Comment by developit** [comment]
I found the bug, will release a fix very shortly!

**Comment by developit** [comment]
Another wishful close perhaps, but `preact@5.1.0-beta.20` should fix the issue you pointed out @kay-is 🎱

**Comment by slmgc** [comment]
@developit sadly, I'm still getting  ```[react-router] Location "/" did not match any routes``` error even though there is a proper route: https://github.com/slmgc/preact-baobab-template/blob/dev/src/common/routes.js#L5

```
"preact": "5.1.0-beta.20",
"preact-compat": "1.8.2",
```

**Comment by kay-is** [comment]
@developit This fixed my bug, but now I got an issue like @slmgc 

The `/` route seems to work, since the navigation is rendered, but every route inside that isn't recognized.

`Warning: [react-router] Location "/map" did not match any routes`
`Warning: [react-router] Location "/settings" did not match any routes`

This is my route definition:

```
export const Main = () =>

  <Router history={browserHistory}>

    <Route path='/' component={App}>
      <IndexRoute component={Map}/>
      <Route path='map' component={Map}/>
      <Route path='settings' component={Settings}/>
      <Route path='*' component={NotFound}/>
    </Route>

  </Router>

const App = props =>
  <div>

    <Navigation>
      <Link to='/map'>Map</Link>
      <Link to='/settings'>Settings</Link>
    </Navigation>

    {props.children}

  </div>

const NotFound = () => <h1>404 - Not Found</h1>
```

**Comment by developit** [comment]
Thanks for the minimal repro. I'm debugging this now and have found the likely cause.

**Comment by developit** [comment]
@kay-is Alright, that repro now appears to be working with `preact-compat@1.9.0` and `preact@5.1.0-beta.20`: http://jsfiddle.net/developit/wtpfyfnt/17/

**Comment by slmgc** [comment]
@developit I've tried to use preact with my 19k LoC project, runs smoothly, react-router works, all seems ok, excellent job! 👍

**Comment by slmgc** [comment]
@developit I've tried to use preact with my 19k LoC application and it seemed that all is ok until I've stumbled upon an issue with redirects. Here's the minimal failing example:

```js
import {Redirect, Route} from 'react-router'
const Home = () => <div>Home</div>

<Route>
      <Route path="/home" component={Home} />
      <Redirect from="*" to="/home" />
</Route>
```

It fails with `[react-router] Location "/" did not match any routes` and works if you'll try to go to `/home` directly. I've checked it with `hashHistory` as well as `browserHistory`.

**Comment by kay-is** [comment]
@developit Yes, 1.9.0 works now with the nested routes.

But ....! ;) 

The `<IndexRoute>` doesn't work. Maybe the same issue that @slmgc has with `<Redirect>`?

It also doesn't work in your fiddle example. Home is never displayed.

**Comment by developit** [comment]
Ah OK, I wondered about that. I'll see what's causing those issues.

**Comment by slmgc** [comment]
@developit do you think we should reopen this issue so everyone knows it's being worked on?

**Comment by developit** [comment]
Yes :)

**Comment by timdorr** [comment]
Anything I can help with? (Router committer here)

**Comment by developit** [comment]
Hi Tim - the remaining issue is that for some reason `IndexRoute` and `Redirect` don't work.  If it's similar to the previous issue, I'm thinking the process of creating the nested routes definition is failing to see these two types of VNodes.

**Comment by timdorr** [comment]
Sounds like there's a difference in how `props.children` works in Preact? (Sorry if these are pedantic questions. I'm not (yet!) a Preact user) Are the `ReactElement`s that API provides anything different? We read through them to [create "route" elements from those `ReactElement`s](https://github.com/reactjs/react-router/blob/92824f606071cd1ee383a3509e26f36016a35bb2/modules/RouteUtils.js#L55), so maybe there is some API difference in how you represent those elements? Interestingly, it's only those Route types that have a customized `createRouteFromReactElement`, so there could be an API difference there.

**Comment by slmgc** [comment]
@developit I think I have found the root of this problem: I'm not entirely sure but it looks like static methods of components aren't inherited with preact, which leads to:

```
// Component classes may have a static create* method.
if (element.type.createRouteFromReactElement) {
```

being falsely in `RouteUtils.js` (which is not the case with React). As a result it leads to a routes object containing:

```
[{
  "childRoutes":[
    {"path":"/", "component": function},
    {"from":"*","to":"/"}
  ]
}]
```

instead of:

```
[{
  "childRoutes":[
    {"path":"/", "component": function},
    {"from":"*","onEnter": function, "to":"/", "path": "*"}
  ]
}]
```
You could see it contains ```onEnter``` method.

**Comment by developit** [comment]
@slmgc Amazing, I can't believe I didn't catch that. I've just added support for `statics` to `createClass()`. It's released as `preact-compat@1.11.0`.

**Comment by developit** [comment]
@timdorr Sorry for missing your points there!  It looks like the issue @slmgc noticed is related to your last point. Preact's `VNode` is different from `ReactElement` - the goal of `preact-compat` is to patch those differences (aliasing `attributes` as `props` and so on).

**Comment by developit** [comment]
Ladies and Gentlemen, I believe we now have full support for react-router!
http://jsfiddle.net/developit/wtpfyfnt/

<img width="192" src="https://i.gyazo.com/4d1b708753b7b3dc43aa935389f9334a.gif">

**Comment by Creeplays** [comment]
Eww... Dont work with
```
"react-router": "^3.0.2",
"preact": "^7.2.0",
"preact-compat": "^3.13.1",
```

**Comment by developit** [comment]
@Creeplays would need more details to actually debug. Do you have a repro?

**Comment by hassanbazzi** [comment]
I'm getting the following: 

```
WARNING in ./~/react-router/es/InternalPropTypes.js
4:13-22 "export 'PropTypes' was not found in 'react'
```

**Comment by developit** [comment]
@hassanbazzi sounds like you're using Webpack 2 but not transpiling `node_modules`. Change your aliases to this:

```js
alias: {
  'react': 'preact-compat/dist/preact-compat',
  'react-dom': 'preact-compat/dist/preact-compat'
}
```

**Comment by yichenlivened** [comment]
```
import { render } from "preact";
import React from "react";
import ReactDOM from "react-dom";
import { Router, IndexRoute, Route, browserHistory } from "react-router";
import { LayoutPortal, LayoutTabs } from "./app/components/index";
import { Login, Register } from "./app/index";

if (process.env.NODE_ENV === "development") {
	const a11y = require("react-a11y");
	a11y(React, { ReactDOM });
}

const App = () => (
	<Router history={browserHistory}>
		<Route component={LayoutPortal}>
			<Route path="/" component={LayoutTabs}>
				<IndexRoute component={Login} />
				<Route path="login" component={Login} />
				<Route path="register" component={Register} />
			</Route>
		</Route>
	</Router>
);

render(<App />, document.getElementById("earth-portal-app"));
```

And I changed my aliases to this: 
```
	resolve: {
		alias: {
			// allow using react components in preact
			"react": "preact-compat",
			"react-dom": "preact-compat"
		}
	},
```

But it keep giving this error:
```
Error: Required prop `history` was not specified in `Router`.

Uncaught TypeError: Cannot read property 'location' of undefined.
```

**Comment by developit** [comment]
I don't think `browserHistory` is something you import from `react-router`. Usually it is done like this:

```js
import { createBrowserHistory } from 'history';

<Router history={createBrowserHistory()}>
```

**Comment by ruiaraujo** [comment]
@developit react-router has included browserHistory since version 2.

**Comment by developit** [comment]
What version are you using? It's not included in version 4.

**Comment by ruiaraujo** [comment]
in v2 and v3 it is included. I haven't checked v4 yet.

**Comment by developit** [comment]
Sorry, I think I was unclear: do you know what version of React Router you have installed?  If you're importing things from `react-router` and they are `null`, that would seem to indicate you have a version you weren't expecting (like building as if you're getting version 3, but version 4 is installed).

**Comment by seeden** [comment]
@developit I am not able to use preact-compat/dist/preact-compat because I see Uncaught Error: Cannot find module "react-dom/server". server.js is just in the root directory

**Comment by timdorr** [comment]
@seeden You don't have to do that since [3.14.0](https://github.com/developit/preact-compat/releases/tag/3.14.0). Just alias `preact-compat` directly.

**Comment by seeden** [comment]
@timdorr it is not working with webpack 2 tree shaking (modules = false)

**Comment by timdorr** [comment]
Well, that would be a separate issue then. This is a very old issue about react router. I would open up something new if that's not working.

**Comment by developit** [comment]
Yup, new issue would be best.  The error is caused by Webpack/babel freezing the exports of ES Modules, which are enabled now that you're using `modules:false`.  React Hot Loader then tries to mutate these, which triggers an exception.

FWIW you won't see any file size difference for `preact-compat` with tree shaking enabled.

**Comment by lucasljj** [comment]
For me the preact-compat only works with react-router in version 3.0.3, if I install 3.0.4+ i get the runtime error: "Uncaught TypeError: _this.setState is not a function" on that line: https://github.com/ReactTraining/react-router/blob/v3/modules/Router.js#L105

But I think the react-router is not the cause of this error because with React i don't get that error

preact: 8.1.0
preact-compat: 3.14.3

react: 15.5.4
react-dom: 15.5.4

test repo: https://github.com/lucasljj/preact-compat-issue-repo

**Comment by lucasljj** [comment]
note: I tried with preact 7.2 and 7.1 and get the same error

**Comment by developit** [comment]
React Router v3 [now exports ES5](https://github.com/ReactTraining/react-router/blob/v3/package.json#L13-L14) and your webpack setup is picking it up.  If you want to use that, you'll need to run `babel-loader` on the source. Otherwise you can alias `'react-router': 'react-router/lib'`.

**Comment by DrewML** [comment]
Hey @developit! This issue with `_this.setState is not a function` is happening with the precompiled version (I think @lucasljj may have just linked to the original source to help out).

![image](https://cloud.githubusercontent.com/assets/5233399/25112687/74d906c8-23b8-11e7-9e20-766036e2d5d6.png)

If it helps at all, here is what the proto chain for `_this` currently consists of in that breakpoint (apologies for the incoming image spam)

![image](https://cloud.githubusercontent.com/assets/5233399/25112725/b4826a1c-23b8-11e7-8e7f-4169dfba9fee.png)

Happy to dig in and grab more info if you have any hunches of what I should be looking for. Can also shoot you a link to the project if you need a repro case (not open-source _quite_ yet, but can give you access). You're a busy busy man, though, so no rush at all 😸

**Comment by developit** [comment]
That is a veeery odd looking component... it seems like maybe it's inheriting in a strange way.. shallow or via prototype copying or something.

I'd be happy to take a look if you're able to provide access.

**Comment by DrewML** [comment]
Figured it out. It looks like the new release of `react-router` is using the new [`create-react-class`](https://www.npmjs.com/package/create-react-class) package that was introduced so the React team could deprecate `createClass` from core. I temporarily fixed the issue in my project by adding `create-react-class.js`:

```js
// create-react-class.js
const { createClass } = require('preact-compat');
module.exports = createClass;
```

and then setup an alias for `create-react-class` to point to my JS file. Since consumers of `create-react-class` expect a default export, I guess you can't just alias to `preact-compat`. Maybe just publishing a `create-preact-class` package and documenting in the README for `preact-compat` is enough?

**Comment by developit** [comment]
Ahh that actually seems like something we're going to want to fix in preact-compat and document. Likely we'll need to provide an alias.

**Comment by DrewML** [comment]
@developit Happy to PR if you let me know how you want to fix it. Maybe

```js
alias: {
    'create-react-class': 'preact-compat/createClass'
}
```

**Comment by developit** [comment]
That would be amazing! I'd actually suggest throwing it in lib since that's already set up:

```js
// lib/create-react-class.js
module.exports = require('preact-compat').createClass;
```

```
alias: {
  'create-react-class': 'preact-compat/lib/create-react-class'
}
```
